# Generated by Django 5.2.3 on 2025-07-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chatroom_created_at_alter_chatroom_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('token_verificacao', models.CharField(blank=True, max_length=36, null=True)),
                ('token_expiracao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
