# Generated by Django 5.2.3 on 2025-07-15 12:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_usuario_descricao_usuario_emoji_usuario_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='dias_consecutivos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_acesso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
