# Generated by Django 5.2.3 on 2025-07-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_usuario_criado_em_usuario_dias_consecutivos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('capa', models.URLField(blank=True)),
                ('privado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='amigos',
            field=models.ManyToManyField(blank=True, to='chat.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='clubes',
            field=models.ManyToManyField(blank=True, to='chat.clube'),
        ),
    ]
