# Generated by Django 5.2.3 on 2025-07-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_mensagem_options_mensagem_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
    ]
