# Generated by Django 5.2.3 on 2025-07-16 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_mensagem_audio_alter_mensagem_conteudo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_nome', models.CharField(max_length=20)),
                ('texto', models.TextField(max_length=150)),
                ('reacoes', models.CharField(blank=True, max_length=20)),
                ('data', models.DateField(auto_now_add=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recados_recebidos', to='chat.usuario')),
            ],
        ),
    ]
