# Generated by Django 5.2.3 on 2025-07-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_recado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recado',
            old_name='avatar_url',
            new_name='foto',
        ),
        migrations.RemoveField(
            model_name='recado',
            name='autor_nome',
        ),
        migrations.AddField(
            model_name='recado',
            name='autor',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recado',
            name='left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recado',
            name='top',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recado',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recado',
            name='texto',
            field=models.TextField(),
        ),
    ]
