# Generated by Django 5.2.3 on 2025-07-16 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_rename_avatar_url_recado_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recado',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recado',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recado',
            name='foto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recado',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.usuario'),
        ),
    ]
