# Generated by Django 5.2.3 on 2025-07-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_recado_autor_alter_recado_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recado',
            name='z_index',
            field=models.IntegerField(default=1),
        ),
    ]
