# Generated by Django 5.2.3 on 2025-07-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_remove_clube_capa_remove_clube_privado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clube',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='data',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='dono',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='membros',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='mods',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='tipo',
        ),
        migrations.AddField(
            model_name='clube',
            name='capa',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='clube',
            name='privado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clube',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
