# Generated by Django 5.2.3 on 2025-07-17 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_remove_clube_categoria_remove_clube_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clube',
            name='capa',
        ),
        migrations.RemoveField(
            model_name='clube',
            name='privado',
        ),
        migrations.AddField(
            model_name='clube',
            name='categoria',
            field=models.CharField(default='Cotidiano', max_length=50),
        ),
        migrations.AddField(
            model_name='clube',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='clube',
            name='dono',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clube',
            name='idioma',
            field=models.CharField(default='Português (Brasil)', max_length=50),
        ),
        migrations.AddField(
            model_name='clube',
            name='imagem',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clube',
            name='membros',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clube',
            name='mods',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clube',
            name='tipo',
            field=models.CharField(choices=[('Pública', 'Pública'), ('Privada', 'Privada'), ('Fechada', 'Fechada')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clube',
            name='descricao',
            field=models.TextField(),
        ),
    ]
