# Generated by Django 5.2.3 on 2025-07-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_remove_clube_capa_remove_clube_privado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='midia',
            field=models.FileField(blank=True, null=True, upload_to='midias/'),
        ),
    ]
