# Generated by Django 5.2.3 on 2025-07-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_topico_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='autor',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='topico',
            name='autor',
            field=models.CharField(max_length=150),
        ),
    ]
