# Generated by Django 5.2.3 on 2025-07-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_alter_resposta_autor_alter_topico_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topico',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topico',
            name='clube',
            field=models.CharField(max_length=100),
        ),
    ]
