# Generated by Django 5.2.3 on 2025-07-24 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_alter_topico_autor_alter_topico_clube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topico',
            name='clube',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='chat.clube'),
        ),
    ]
