# Generated by Django 5.2.3 on 2025-07-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_alter_topico_clube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='autor',
            field=models.CharField(max_length=100),
        ),
    ]
