# Generated by Django 5.2.3 on 2025-07-25 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_alter_resposta_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='resposta_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas_filhas', to='chat.resposta'),
        ),
    ]
