# Generated by Django 5.2.3 on 2025-07-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_resposta_resposta_pai'),
    ]

    operations = [
        migrations.AddField(
            model_name='topico',
            name='arquivo_midia',
            field=models.FileField(blank=True, null=True, upload_to='topicos_midias/'),
        ),
    ]
