# Generated by Django 5.2.3 on 2025-07-26 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_topico_arquivo_midia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaDeBatePapo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_de_bate_papo', to='chat.clube')),
            ],
        ),
        migrations.CreateModel(
            name='MensagemDaSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat.saladebatepapo')),
            ],
        ),
    ]
