# Generated by Django 5.2.3 on 2025-07-26 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_saladebatepapo_mensagemdasala'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='chat.clube')),
            ],
        ),
        migrations.AlterField(
            model_name='mensagemdasala',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat.sala'),
        ),
        migrations.DeleteModel(
            name='SalaDeBatePapo',
        ),
    ]
