# Generated by Django 5.2.3 on 2025-07-26 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_sala_alter_mensagemdasala_sala_delete_saladebatepapo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='chat.sala')),
            ],
        ),
        migrations.DeleteModel(
            name='MensagemDaSala',
        ),
    ]
