# Generated by Django 5.2.3 on 2025-07-26 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_salamensagem_delete_mensagemdasala'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nome', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('rejeitado', models.BooleanField(default=False)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='chat.clube')),
            ],
            options={
                'unique_together': {('clube', 'usuario_nome')},
            },
        ),
    ]
