# Generated by Django 5.2.3 on 2025-07-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0029_solicitacaoclube'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaoclube',
            name='foto_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
