# Generated by Django 5.2.3 on 2025-07-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0030_solicitacaoclube_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='visto_por',
            field=models.ManyToManyField(blank=True, related_name='mensagens_vistas', to='chat.usuario'),
        ),
    ]
