# Generated by Django 5.2.3 on 2025-07-28 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0031_mensagem_visto_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='eventos/banners/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='chat.clube')),
            ],
        ),
    ]
