# Generated by Django 5.2.3 on 2025-07-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0032_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='criado_em',
        ),
        migrations.AlterField(
            model_name='evento',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_banners/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_fim',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(),
        ),
    ]
