# Generated by Django 5.2.3 on 2025-07-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0033_remove_evento_criado_em_alter_evento_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueados',
            field=models.ManyToManyField(blank=True, related_name='bloqueado_por', to='chat.usuario'),
        ),
    ]
