# Generated by Django 5.2.3 on 2025-08-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0034_usuario_bloqueados'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
