# Generated by Django 5.2.3 on 2025-08-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0036_novidade_tema_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
