# Generated by Django 5.2.3 on 2025-08-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0037_pixel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WPlaceDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Pixel',
        ),
    ]
