# Generated by Django 5.2.3 on 2025-08-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0038_wplacedrawing_delete_pixel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WPlaceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elements', models.JSONField(default=list)),
                ('offset_x', models.FloatField(default=0)),
                ('offset_y', models.FloatField(default=0)),
                ('zoom', models.FloatField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WPlaceDrawing',
        ),
    ]
